/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>
// register address
#define GPIOA_BASE 0x40010800
#define GPIOx_CRL *(volatile uint32_t *)(GPIOA_BASE + 0x0)
#define AFIO_EXTICR1 *(volatile uint32_t *)(GPIOA_BASE + 0x8)
#define GPIOA_CRH *(volatile uint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR *(volatile uint32_t *)(GPIOA_BASE + 0x0C)

#define RCC_CR  *(volatile uint32_t *)(RCC_BASE + 0x0)
#define RCC_BASE 0x40021000
#define RCC_APB2ENR  *(volatile uint32_t *)(RCC_BASE + 0x18)

#define EXTI_base 0x40010400
#define EXTI_IMR *(volatile uint32_t *)(EXTI_base + 0x0)
#define EXTI_RTSR *(volatile uint32_t *)(EXTI_base + 0x8)
#define EXTI_PR *(volatile uint32_t *)(EXTI_base + 0x14)
#define NVIC_ISER0 *(volatile uint32_t *)(0xE000E100)

void clock_init()
{
	RCC_CR |= 0<<0;
	RCC_APB2ENR |= 1<<2;
	RCC_APB2ENR |= 1<<0;
}
int main(void)
{
	 clock_init();
	// Set portA0 to input floating
	GPIOx_CRL |= 0b0100;

	// Set pin 13 output
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0b0010 << 20;
	//output at pin13
	//GPIOA_ODR |= 1<<13;

	// remap to ext0
	AFIO_EXTICR1 |=  0b0000<<0;
	//Rising edge enabled
	EXTI_RTSR |= 1<<0;
	//Enable Mask
	EXTI_IMR |= 1<<0;
	//Enable VIC IRQ6
	NVIC_ISER0 |= 1<<6;
	while(1);

}
void EXTI0_IRQHandler(void)
{

	//toggle output at pin13
	GPIOA_ODR ^= 1<<13;
	//pending request (write 1 to clear)
	EXTI_PR =1<<0;

}
