/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f103c6.h"
#include "GPIO_driver.h"
#include "EXTI_driver.h"
#include "USART.h"
USART_CONFIG config;
uint16_t ch,ch2;
void IRQ()
{
	MCAL_USART_RECEIVE_DATA(USART1, &ch, disable,&config);
	MCAL_USART_SEND_DATA(USART2, &ch, enable,&config);

}
void IRQ2()
{
//	MCAL_USART_RECEIVE_DATA(USART2, &ch2, disable,&config);
//	MCAL_USART_SEND_DATA(USART2, &ch2, enable,&config);


}
int main()
{

	clk_enable(GPIOA,RCC);
	clk_enable(GPIOB,RCC);
	clk_enable_AFIO();


	config.BAUD_RATE=115200;
	config.flow_ctrl=USART_flow_ctrl_none;
	config.USART_MODE=USART_MODE_TX_RX;
	config.IRQ_enable=USART_IRQ_enable_RXNEIE;
	config.P_IRQ_callBack=IRQ;
	config.parity=USART_Parity_disabled;
	config.payload_length=USART_BAUD_payload_length_8;
	config.stop_bits=USART_Stop_bits_1;
	MCAL_USART_INIT(USART1, &config);
	MCAL_USART_GPIO_SET_PINS(USART1);
	config.BAUD_RATE=230400;
		config.flow_ctrl=USART_flow_ctrl_none;
		config.USART_MODE=USART_MODE_TX_RX;
		config.IRQ_enable=USART_IRQ_enable_RXNEIE;
		config.P_IRQ_callBack=IRQ2;
		config.parity=USART_Parity_disabled;
		config.payload_length=USART_BAUD_payload_length_8;
		config.stop_bits=USART_Stop_bits_1;
		MCAL_USART_INIT(USART2, &config);
		MCAL_USART_GPIO_SET_PINS(USART2);
	while(1);


}
