/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f103c6.h"
#include "GPIO_driver.h"
#include "EXTI_driver.h"
#include "LCD.h"
#include "keypad.h"

uint8_t flag=0;
void EXTI9_CALLBACK()
{
	LCD_clear_screen();
	flag = 1;
	LCD_WRITE_STRING("IRQ EXTI 9 is happened");
	LCD_clear_screen();
}
void delay()
{
	unsigned int i;
	for(i=0;i<100000;i++);
}




int main()
{

	clk_enable(GPIOA,RCC);
	clk_enable(GPIOB,RCC);
	clk_enable_AFIO;
	LCD_INIT();
	LCD_clear_screen();
	Keypad_init();
	unsigned char key_pressed;

	EXTI_PinConfig_t EXTI_CONF;
	EXTI_CONF.EXTI_PIN= EXTI9PB9;
	EXTI_CONF.Trigger_case = EXT_Trigger_Rising;
	EXTI_CONF.P_IRQ_Call_Back = EXTI9_CALLBACK;
	EXTI_CONF.IRQ_EN = EXT_Enable;
	MCAL_EXTI_GPIO_INIT(&EXTI_CONF);
	flag=1;
	while(1)
	{
		key_pressed = Keypad_getkey();
		switch (key_pressed)
		{
		case 'A':
			break;
		case '?':
			LCD_clear_screen();
			break;
		default:
			LCD_WRITE_CHAR(key_pressed);
			break;
		}
		if(flag)
		{
			LCD_clear_screen();
			flag=0;
		}



	}

}
