/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "stm32f103c6.h"
#include "GPIO_driver.h"
#include "EXTI_driver.h"
#include "USART.h"
#include "SPI.h"

//#define MCU_Acts_as_Master
#define MCU_Acts_as_SLAVE

USART_CONFIG config;
uint16_t ch,ch2;
void SPI1_Call_back(struct S_IRQ_src IRQ)
{
#ifdef MCU_Acts_as_SLAVE
	if(IRQ.RXNE)
	{

		MCAL_SPI_TX_RX(SPI1, &ch, disabled);
		MCAL_USART_SEND_DATA(USART1, &ch, enable,&config);
	}

#endif
}
void IRQ()
{
	MCAL_USART_RECEIVE_DATA(USART1, &ch, disable,&config);
	MCAL_USART_SEND_DATA(USART1, &ch, enable,&config);

	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 0);
	MCAL_SPI_TX_RX(SPI1, &ch, enabled);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);

}

int main()
{

	clk_enable(GPIOA,RCC);
	clk_enable(GPIOB,RCC);
	clk_enable_AFIO();

	//UART
	config.BAUD_RATE=115200;
	config.flow_ctrl=USART_flow_ctrl_none;
	config.USART_MODE=USART_MODE_TX_RX;
	config.IRQ_enable=USART_IRQ_enable_RXNEIE;
	config.P_IRQ_callBack=IRQ;
	config.parity=USART_Parity_disabled;
	config.payload_length=USART_BAUD_payload_length_8;
	config.stop_bits=USART_Stop_bits_1;
	MCAL_USART_INIT(USART1, &config);
	MCAL_USART_GPIO_SET_PINS(USART1);

	//SPI
	SPI_config_t SPI_CONF;
	SPI_CONF.Clk_Polarity=SPI_ClkPolarity_high_when_idle;
	SPI_CONF.Clk_phase=SPI_Data_capture_at_SecondClkEdge;
	SPI_CONF.Data_size=SPI_data_size_8bit;
	SPI_CONF.Frame_format=SPI_Frame_format_MSB_transmitted_first;
	SPI_CONF.Baud_Rate_Prescalar=SPI_Baud_Rate_Prescalar_8;
	SPI_CONF.Communication_Mode=SPI_DIRECTION_2_LINES;

#ifdef MCU_Acts_as_Master
	SPI_CONF.Device_Mode=SPI_Device_Mode_MASTER;
	SPI_CONF.IRQ_Enable=SPI_IRQ_Enable_none;
	SPI_CONF.NSS=SPI_NSS_Internal_soft_set;
	SPI_CONF.P_IRQ_call=NULL;

	GPIO_PinConfig_t Pin;
	Pin.GPIO_PinNumber=GPIO_PIN_4;
	Pin.GPIO_MODE=GPIO_MODE_OUTPUT_PP;
	Pin.GPIO_Output_speed=GPIO_SPEED_10M;
	MCAL_GPIO_Init(GPIOA, &Pin);
	MCAL_GPIO_WritePin(GPIOA, GPIO_PIN_4, 1);
#endif
#ifdef MCU_Acts_as_SLAVE
	SPI_CONF.Device_Mode=SPI_Device_Mode_SLAVE;
	SPI_CONF.IRQ_Enable=SPI_IRQ_Enable_RXNIE;
	SPI_CONF.NSS=SPI_NSS_hard_slave;
	SPI_CONF.P_IRQ_call=SPI1_Call_back;

#endif

	MCAL_SPI_Init(SPI1,&SPI_CONF);
	MCAL_SPI_GPIO_SET_PINS(SPI1);

	while(1);


}
